#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running tests..."
pnpm test

echo "Verifying architectural integrity..."
pnpm verify:structure
pnpm verify:app-routes
pnpm verify:feature-routes
pnpm verify:no-cross-feature-imports
