#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm verify:structure
pnpm verify:app-routes
pnpm verify:feature-routes
pnpm verify:no-cross-feature-imports
pnpm verify:theme-contract
pnpm verify:no-raw-colors
pnpm verify:tokens
pnpm lint
pnpm typecheck
